name: Latest zenn post workflow
on: 
    schedule:
      interval: daily
      time: '7:00'
      timezone: Asia/Tokyo
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: gautamkrishnar/blog-post-workflow@v1
              with: 
                max_post_count: "5"
                feed_list: "https://zenn.dev/jonghyo/feed"